#!/bin/bash
# ========================================================================
# Copyright (c) by Hitachi, 2024. All rights reserved.
# ========================================================================
#
# HCP for Cloud Scale script - insert_sizes_1dir.sh
#
# This scripts generates a partition range file with size for each partition.
# It requires two types of files in each specified directory:
#  * Parsed partition state file generated by ./hcpcs_parse_partitions_state.sh script
#  * Partition range file generated by ./super_parse_partition_map.sh script
# 
#
###########################################################################

DIR_DEFAULT="$(pwd)"
DIR=${1:-"$DIR_DEFAULT"}
FILE1=${2:-"partitions_ranges.all.txt"}
FILE_STATE=${3:-"supportLogs/hcpcs_parse_partitions_state.log"}

function usage() {
  echo "This scripts generates a partition range file with size for each partition.
It requires two types of files in each specified directory:
  * Parsed partition state file generated by ./hcpcs_parse_partitions_state.sh script
  * Partition range file generated by ./super_parse_partition_map.sh script

  $0 <directory> <partition_ranges_file> <parsed_partition_state>
  where
   directory                 - directory with two input files 
                               default: current directory
   partition_ranges_file     - file created by super_parse_partition_map.sh
                               default: $FILE1
   parsed_partition_state    - parsed partition state file
                               default: $FILE_STATE
"
}

if [[ "$1" == "-h" ]] ; then
  usage
  exit
fi

function progress() {
   echo "$1" >&2
}

function log() {
   echo "$1" >> $OUTPUT_FILE
}

FILE_STATE_PATH="$DIR/$FILE_STATE"

count=0
filewithsize=$(echo "$DIR/${FILE1/.txt/_size.txt}")

if [ ! -f ${DIR}/${FILE1} ]; then
    progress "ERROR: FILE NOT FOUND: ${DIR}/${FILE1}"
    exit
fi

if [ ! -f ${DIR}/${FILE_STATE} ]; then
    progress "ERROR: FILE NOT FOUND: ${DIR}/${FILE_STATE}"
    exit
fi

state_file_lines=$(cat ${DIR}/${FILE_STATE} | wc -l)
if (( $state_file_lines < 15 )); then
    progress "ERROR: ${DIR}/${FILE_STATE} IS TOO SMALL"
    exit
fi


if [ -f $filewithsize ]; then
    rm -f $filewithsize
    touch $filewithsize
fi

num_partitions=$(cat "${DIR}/${FILE1}" | wc -l)
progress "Processing $num_partitions partitions..."

awk 'NR==FNR {map[$1] = $3; next} {print $1, map[$1], substr($0, index($0, $2))}' \
${DIR}/${FILE_STATE} ${DIR}/${FILE1} > ${filewithsize} 

rm -f ${DIR}/${FILE1}

progress "Generated $filewithsize file"
# progress "   $count partitions"
