#!/usr/bin/env bash
# parse_map_ranges.sh - derive simple partition-id ranges from hcpcs_partitions_map.log
set -euo pipefail

_script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
# shellcheck disable=SC1091
. "${_script_dir}/gsc_core.sh"

_map_log="${1:-supportLogs/hcpcs_partitions_map.log}"

echo "Partition map file: ${_map_log}"
echo "Output file:"

if [[ ! -r "${_map_log}" ]]; then
    gsc_log_error "Map log not found: ${_map_log}"
    exit 1
fi

echo "Starting processing..."

: > partitions_ranges_15.txt
: > partitions_ranges_40.txt
: > partitions_ranges_41.txt

# Expected _map_log format (TSV), as generated by hcpcs_parse_partitions_map.sh:
#   partitionId<TAB>leaderNode<TAB>state
while IFS=$'\t' read -r _pid _leader _state; do
    # skip headers or malformed lines
    [[ "${_pid}" =~ ^[0-9]+$ ]] || continue
    _mod=$((_pid % 3))
    case "${_mod}" in
        0) echo "${_pid}" >> partitions_ranges_15.txt ;;
        1) echo "${_pid}" >> partitions_ranges_40.txt ;;
        2) echo "${_pid}" >> partitions_ranges_41.txt ;;
    esac
done < "${_map_log}"

for _f in partitions_ranges_15.txt partitions_ranges_40.txt partitions_ranges_41.txt; do
    _count=$(wc -l < "${_f}" || echo 0)
    echo "Created ${_f} file with ${_count} partitions"
done
