#!/bin/bash

source "$SERVICE_PACKAGE_DIR/svcbin/service-funcs.sh"

CONTAINER=kafka-service

KAFKA_DATA="$SERVICE_DATA_DIR"
KAFKA_LOG4J="$KAFKA_DATA/log4j.properties"

if [[ ! -f "$KAFKA_LOG4J" ]]
then
    apply_sed "$SERVICE_PACKAGE_DIR/log4j.properties.src" "$KAFKA_LOG4J" "s#HOSTLOGS#$SERVICE_LOG_DIR#"
fi

redirect_to_log $CONTAINER

export KAFKA_LOG_DIRS="$SERVICE_DATA_DIR/0/",
export KAFKA_CONFIG="$SERVICE_PACKAGE_DIR/conf"

KAFKA_HOME="/opt/kafka_2.11-1.1.0/"
KAFKA_SRC="$KAFKA_CONFIG/server.properties.src"
KAFKA_PROPS="$KAFKA_HOME/config/server.properties"
KAFKA_ADVERTISED_HOST_NAME=$($SERVICE_TOOLS_DIR/localIp.sh)
KAFKA_ZOOKEEPER_CONNECT=$($SERVICE_TOOLS_DIR/zookeeperUrl.sh kafka)
KAFKA_BROKER_PROTO_VERSION=${KAFKA_BROKER_PROTO_VERSION:-"1.1.0"}
KAFKA_LOG_MSG_FORMAT_VERSION=${KAFKA_LOG_MSG_FORMAT_VERSION:-"1.1.0"}
KAFKA_CONFIG_REPLICATION_FACTOR=${KAFKA_CONFIG_REPLICATION_FACTOR:-"1"}

export KAFKA_LOG4J_OPTS="-Dlog4j.configuration=file:$KAFKA_LOG4J"
export KAFKA_OPTS="$ZK_BUFFER_SIZE"
export KAFKA_JMX_OPTS="-Dcom.sun.management.jmxremote=false"

if [[ -n "${!BOUND_PORT_DEF_PRIMARY_PORT}" ]]; then
    export KAFKA_PORT=${!BOUND_PORT_DEF_PRIMARY_PORT}
fi

$SERVICE_TOOLS_DIR/serviceInit.sh

apply_sed "$KAFKA_SRC" "$KAFKA_PROPS" "s#BROKER_ID#$KAFKA_BROKER_ID#;s#PORT#${!BOUND_PORT_DEF_PRIMARY_PORT}#;s#ADVERTISED_HOST_NAME#$KAFKA_ADVERTISED_HOST_NAME#;s#ZOOKEEPER_CONNECT#$KAFKA_ZOOKEEPER_CONNECT#;s#LOG_DIRS#$KAFKA_LOG_DIRS#;s#BROKER_PROTOCOL_VERSION#$KAFKA_BROKER_PROTO_VERSION#;s#LOG_MSG_FORMAT_VERSION#$KAFKA_LOG_MSG_FORMAT_VERSION#;s#REPLICATION_FACTOR#$KAFKA_CONFIG_REPLICATION_FACTOR#;"

cp $SERVICE_PACKAGE_DIR/svcbin/kafka-server-start.sh /opt/kafka_2.11-1.1.0/bin/kafka-server-start.sh
ln -s $SERVICE_LOG_DIR $KAFKA_HOME/logs
exec $KAFKA_HOME/bin/kafka-server-start.sh "$KAFKA_PROPS"
