{
 "title": "HCP for Cloud Scale - Dashboard 6: Services Health",
 "tags": [ "cloudscale" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ClusterName", "label": "Choose  Cluster", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   { "name": "allnodes", "label": "WildCard", "query": ".*" },
   { "name": "excl_net", "label": "Exclude_Device", "query": "^docker.*$|^lo$" }
  ]
 },
 "panels": [
  {
   "title": "S3-Gateway and Metadata-Gateway Balance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "S3 I/O distribution",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (http_s3_servlet_operations_total{job=\"S3-Gateway\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "S3 I/O Imbalance (by Node)",
   "type": "table",
   "description": "0-15% = is acceptable imbalance",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "abs(100-100*(sum by (instance) (http_s3_servlet_operations_total{})  / on() group_left() (sum(http_s3_servlet_operations_total{}) / sum (up{job=\"S3-Gateway\"}))))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Metadata Gateway Balance",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (metadataInstanceId) (mcs_partitions_per_instance)"
    }
   ]
  },
  {
   "title": "Metadata Partition Balance (by Node)",
   "type": "table",
   "description": "A Database should be distributed evenly among nodes. Any node showing >15% imbalance should be investigated.",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "mcs_partitions_per_instance", "legendFormat": "Total" }
   ]
  },
  { "title": "Database Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Total DB Partition count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (mcs_copies_per_partition)"
    }
   ]
  },
  {
   "title": "3x Fully Protected Partitions",
   "type": "stat",
   "description": "Partitions with 3 copies are fully protected",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (mcs_copies_per_partition==3)"
    }
   ]
  },
  {
   "title": "Degraded - 2x Protected Partitions",
   "type": "stat",
   "description": "DB Partitions with 2 copies are functional, but not fully protected",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (mcs_copies_per_partition==2)"
    }
   ]
  },
  {
   "title": "Unprotected Partitions (1x)",
   "type": "stat",
   "description": "DB Partitions with 1 copy are not functional (unprotected) - any PUT operation requiring these partitions will fail.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (mcs_copies_per_partition==1)"
    }
   ]
  },
  {
   "title": "Orphaned Partitions (no copies)",
   "type": "stat",
   "description": "DB Partitions with no copies are not functional - they are likely orphaned and to be deleted by the system later.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (mcs_copies_per_partition==0)"
    }
   ]
  },
  {
   "title": "Overprotected  Partitions (4x+)",
   "type": "stat",
   "description": "Occasionally and temporarily some DB partitions may be overprotected (4+ copies). It's not better or worse than 3 copies. It's a temporary state.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (mcs_copies_per_partition>=4)"
    }
   ]
  },
  {
   "title": "DB Partition Protection",
   "type": "stat",
   "description": "Checks the partitions protection (number of copies)",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((count(count(mcs_copies_per_partition==1) > 0) OR on() vector(0)) * 1000) + ((count(count(mcs_copies_per_partition==2) > 0) OR on() vector(0)) * 100) + ((count(count(mcs_copies_per_partition==3) > 0) OR on() vector(0)) * 1) + ((count(count(mcs_copies_per_partition==0) > 0) OR on() vector(0)) * 2) + ((count(count(mcs_copies_per_partition==4) > 0) OR on() vector(0)) * 10)"
    }
   ]
  },
  {
   "title": "DB Partition Distribution (by Node)",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 4, "y": 11 },
   "targets": [
    {
     "expr": "sum(mcs_partitions_per_instance)",
     "legendFormat": "Total DB Partitions incl. copies (all tables)"
    },
    {
     "expr": "sum by (metadataInstanceId) (mcs_partitions_per_instance)",
     "legendFormat": "Partitions on Node"
    }
   ]
  },
  {
   "title": "DB Partitions by protection level",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 14, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count (mcs_copies_per_partition)",
     "legendFormat": "Total partitions"
    },
    {
     "expr": "count (mcs_copies_per_partition==3)",
     "legendFormat": "3x fully protected partitions"
    },
    {
     "expr": "count (mcs_copies_per_partition==2)",
     "legendFormat": "2x protected partitions"
    },
    {
     "expr": "count (mcs_copies_per_partition==1)",
     "legendFormat": "1x unprotected partitions"
    },
    {
     "expr": "count (mcs_copies_per_partition==0)",
     "legendFormat": "0-copies partitions"
    },
    {
     "expr": "count (mcs_copies_per_partition>3)",
     "legendFormat": "4x+ overprotected partitions"
    }
   ]
  },
  {
   "title": "Database Partitions Per Node",
   "type": "stat",
   "description": "Checks the partitions",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(mcs_partitions_per_instance)"
    }
   ]
  },
  {
   "title": "New partitions added in 7 days",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(mcs_partitions_per_instance[7d]))/3",
     "legendFormat": "Daily new partitions"
    }
   ]
  },
  {
   "title": "Daily new partitions added",
   "type": "timeseries",
   "description": "New raft groups added each day. Each raft group has 3 partitions. The actual number of added partitions is 3x of displayed.",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(delta(mcs_partitions_per_instance[1d]))/3",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Daily new client objects added ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(delta(metadata_clientobject_active_count[1d]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Partitions Size Health",
   "type": "stat",
   "description": "Attention if Partition Size is above 1.5x the default size (1GB is default split threshold).\nAlarm if if Partition Size is above 2x the default size (>2GB).",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(mcs_disk_usage_per_partition)",
     "legendFormat": "{{keySpaceId}}"
    }
   ]
  },
  {
   "title": "Partitions Sizes ",
   "type": "gauge",
   "description": "Partitions may exceed slightly the threshold (1GB) for a short time, but they should not normally continue to grow much above the threshold.",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(mcs_disk_usage_per_partition < 1500000000)",
     "legendFormat": "Normal size"
    },
    {
     "expr": "count(mcs_disk_usage_per_partition < 3000000000) - count(mcs_disk_usage_per_partition < 1500000000) ",
     "legendFormat": "Large"
    },
    {
     "expr": "count(mcs_disk_usage_per_partition >= 3000000000) - count(mcs_disk_usage_per_partition > 5000000000)",
     "legendFormat": "Very Large"
    },
    {
     "expr": "count(mcs_disk_usage_per_partition >= 5000000000)",
     "legendFormat": "Extremely Large"
    }
   ]
  },
  {
   "title": "Largest Partition Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(mcs_disk_usage_per_partition)",
     "legendFormat": "{{keySpaceId}}"
    }
   ]
  },
  {
   "title": "History of Large DB Partitions",
   "type": "timeseries",
   "description": "A large partition is a partition with a size over 1.5GB.\nPartitions under 50% of the threshold (default is 1GB) are considered \"normal\", as the partition split could be delayed. ",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(mcs_disk_usage_per_partition < 3000000000) - count(mcs_disk_usage_per_partition <= 1500000000) ",
     "legendFormat": "Large (1.5-3GB)"
    },
    {
     "expr": "count(mcs_disk_usage_per_partition >= 3000000000)",
     "legendFormat": "Very Large (>3GB)"
    }
   ]
  },
  {
   "title": "DB Information: Keyspaces and Partitions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "Partitions Sizes ",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "mcs_disk_usage_per_partition",
     "legendFormat": "{{keySpaceId}}::{{partitionId}}"
    }
   ]
  },
  {
   "title": "Metadata Gateway Balance",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (metadataInstanceId) (mcs_partitions_per_instance)"
    }
   ]
  },
  {
   "title": "Partitions Capacity Consumed",
   "type": "table",
   "gridPos": { "h": 12, "w": 5, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (metadataInstanceId) (mcs_disk_usage_per_instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Partitions Splits by Keyspace",
   "type": "stat",
   "gridPos": { "h": 12, "w": 7, "x": 17, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mcs_splits_per_keyspace_total", "legendFormat": "{{keySpaceId}}" }
   ]
  },
  {
   "title": "Client Object (15)  - Partitions Count",
   "type": "stat",
   "description": "Number of Leaders",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metadata_leader_count{keySpace=\"15\"})"
    }
   ]
  },
  {
   "title": "Client Objects Partitions Leaders",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metadata_leader_count{keySpace=\"15\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Client Object Partitions (Leaders by Node)",
   "type": "timeseries",
   "description": "Client Object keyspace id = 15",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metadata_leader_count{keySpace=\"15\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Stored Object (40) - Partitions Count",
   "type": "stat",
   "description": "Number of Leaders",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metadata_leader_count{keySpace=\"40\"})"
    }
   ]
  },
  {
   "title": "Stored Objects Partitions Leaders",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metadata_leader_count{keySpace=\"40\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Stored Object Partitions (Leaders by Node)",
   "type": "timeseries",
   "description": "Stored Object keyspace id = 40",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metadata_leader_count{keySpace=\"40\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Stored Object Back Reference (41) - Partitions Count",
   "type": "stat",
   "description": "Number of Leaders",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 69 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metadata_leader_count{keySpace=\"41\"})"
    }
   ]
  },
  {
   "title": "Stored Objects Back Reference Partitions Leaders",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 69 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metadata_leader_count{keySpace=\"41\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Stored Object Back Reference Partitions (Leaders by Node)",
   "type": "timeseries",
   "description": "Stored Object Back Reference keyspace id = 41",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metadata_leader_count{keySpace=\"41\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Data Lifecycle Policies: Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Lifecycle Policies: started-counter by policy type",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 21, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "(sum by (policy) (lifecycle_policy_started)) % 100",
       "legendFormat": "{{policy}}"
      },
      {
       "expr": "(sum by (policy) (lifecycle_policy_started_total)) % 100",
       "legendFormat": "{{policy}}"
      }
     ]
    },
    {
     "title": "Lifecycle Policies: completed-counter by policy type",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 21, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum by (policy) (lifecycle_policy_completed) % 100",
       "legendFormat": "{{policy}}"
      },
      {
       "expr": "sum by (policy) (lifecycle_policy_completed_total) % 100",
       "legendFormat": "{{policy}}"
      }
     ]
    },
    {
     "title": "Lifecycle Policies: records examined by policy type",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 21, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (policy) (lifecycle_policy_examine_latency_seconds_count)",
       "legendFormat": "{{policy}}"
      }
     ]
    },
    {
     "title": "Lifecycle Policies: records accepted by policy type",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 21, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (policy) (lifecycle_policy_accept_latency_seconds_count)",
       "legendFormat": "{{policy}}"
      }
     ]
    },
    {
     "title": "Lifecycle Policies: Rate of examined by policy type",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 21, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (policy) (rate(lifecycle_policy_examine_latency_seconds_count[10m]))",
       "legendFormat": "{{policy}}"
      }
     ]
    },
    {
     "title": "Lifecycle Policies: Rate of accepted by policy type",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 21, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (policy) (rate(lifecycle_policy_accept_latency_seconds_count[10m]))",
       "legendFormat": "{{policy}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Data Lifecycle: DELETE_BACKEND_OBJECTS policy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lifecycle Policies: DELETE BACKEND OBJECTS examined by Nodes",
     "type": "timeseries",
     "description": "DELETE BACKEND OBJECTS policy deletes data objects off the storage components, such as S-nodes",
     "gridPos": { "h": 6, "w": 21, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance) (lifecycle_policy_examine_latency_seconds_count{policy=\"DELETE_BACKEND_OBJECTS\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Lifecycle Policies: DELETE BACKEND OBJECTS accepted by Nodes",
     "type": "timeseries",
     "description": "DELETE BACKEND OBJECTS policy deletes data objects off the storage components, such as S-nodes",
     "gridPos": { "h": 6, "w": 21, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance) (lifecycle_policy_accept_latency_seconds_count{policy=\"DELETE_BACKEND_OBJECTS\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Lifecycle Policies: DELETE BACKEND OBJECTS accepted by Total",
     "type": "timeseries",
     "description": "DELETE BACKEND OBJECTS policy deletes data objects off the storage components, such as S-nodes",
     "gridPos": { "h": 6, "w": 21, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(lifecycle_policy_accept_latency_seconds_count{policy=\"DELETE_BACKEND_OBJECTS\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Data Lifecycle: TOMBSTONE_DELETION policy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lifecycle Policies: TOMBSTONE_DELETION examined by Nodes",
     "type": "timeseries",
     "description": "TOMBSTONE_DELETION policy deletes tombstone DB records ",
     "gridPos": { "h": 6, "w": 21, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance) (lifecycle_policy_examine_latency_seconds_count{policy=\"TOMBSTONE_DELETION\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Lifecycle Policies: TOMBSTONE_DELETION accept by Nodes",
     "type": "timeseries",
     "description": "TOMBSTONE_DELETION policy deletes tombstone DB records ",
     "gridPos": { "h": 6, "w": 21, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance) (lifecycle_policy_accept_latency_seconds_count{policy=\"TOMBSTONE_DELETION\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Lifecycle Policies: TOMBSTONE_DELETION accept Total",
     "type": "timeseries",
     "description": "TOMBSTONE_DELETION policy deletes tombstone DB records ",
     "gridPos": { "h": 6, "w": 21, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(lifecycle_policy_accept_latency_seconds_count{policy=\"TOMBSTONE_DELETION\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Data Lifecycle: VERSION_EXPIRATION policy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lifecycle Policies: VERSION_EXPIRATION examined by Nodes",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 21, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance) (lifecycle_policy_examine_latency_seconds_count{policy=\"VERSION_EXPIRATION\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Lifecycle Policies: VERSION_EXPIRATION accepted by Nodes",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 21, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance) (lifecycle_policy_accept_latency_seconds_count{policy=\"VERSION_EXPIRATION\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Data Lifecycle: CHARGEBACK_POPULATION policy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lifecycle Policies: CHARGEBACK_POPULATION examined by Nodes",
     "type": "timeseries",
     "description": "✔{policy=\"MIRROR_TABLE_MAINTENANCE\"}\n✔{policy=\"INCOMPLETE_MPU_EXPIRATION\"}\n✔{policy=\"DELETE_BACKEND_OBJECTS\"}\n✔{policy=\"CLIENT_OBJECT_POLICY\"}\n✔{policy=\"CHARGEBACK_POPULATION\"}",
     "gridPos": { "h": 6, "w": 21, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance) (lifecycle_policy_examine_latency_seconds_count{policy=\"CHARGEBACK_POPULATION\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Lifecycle Policies: CHARGEBACK_POPULATION accepted by Nodes",
     "type": "timeseries",
     "description": "✔{policy=\"MIRROR_TABLE_MAINTENANCE\"}\n✔{policy=\"INCOMPLETE_MPU_EXPIRATION\"}\n✔{policy=\"DELETE_BACKEND_OBJECTS\"}\n✔{policy=\"CLIENT_OBJECT_POLICY\"}\n✔{policy=\"CHARGEBACK_POPULATION\"}",
     "gridPos": { "h": 6, "w": 21, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance) (lifecycle_policy_accept_latency_seconds_count{policy=\"CHARGEBACK_POPULATION\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Data Lifecycle: INCOMPLETE_MPU_EXPIRATION policy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lifecycle Policies: INCOMPLETE_MPU_EXPIRATION examined by Nodes",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 21, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance) (lifecycle_policy_examine_latency_seconds_count{policy=\"INCOMPLETE_MPU_EXPIRATION\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Lifecycle Policies: INCOMPLETE_MPU_EXPIRATION accepted by Nodes",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 21, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance) (lifecycle_policy_accept_latency_seconds_count{policy=\"INCOMPLETE_MPU_EXPIRATION\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Data Lifecycle: MIRROR_TABLE_MAINTENANCE policy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lifecycle Policies: MIRROR_TABLE_MAINTENANCE examined by Nodes",
     "type": "timeseries",
     "description": "✔{policy=\"MIRROR_TABLE_MAINTENANCE\"}\n✔{policy=\"INCOMPLETE_MPU_EXPIRATION\"}\n✔{policy=\"DELETE_BACKEND_OBJECTS\"}\n✔{policy=\"CLIENT_OBJECT_POLICY\"}\n✔{policy=\"CHARGEBACK_POPULATION\"}",
     "gridPos": { "h": 6, "w": 21, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum by (instance) (lifecycle_policy_examine_latency_seconds_count{policy=\"MIRROR_TABLE_MAINTENANCE\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Lifecycle Policies: MIRROR_TABLE_MAINTENANCE accepted by nodes",
     "type": "timeseries",
     "description": "✔{policy=\"MIRROR_TABLE_MAINTENANCE\"}\n✔{policy=\"INCOMPLETE_MPU_EXPIRATION\"}\n✔{policy=\"DELETE_BACKEND_OBJECTS\"}\n✔{policy=\"CLIENT_OBJECT_POLICY\"}\n✔{policy=\"CHARGEBACK_POPULATION\"}",
     "gridPos": { "h": 6, "w": 21, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "sum by (instance) (lifecycle_policy_accept_latency_seconds_count{policy=\"MIRROR_TABLE_MAINTENANCE\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Microservice Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Service anomalies detected",
     "type": "barchart",
     "description": "Helps to identify service \"up\" anomalies during the reporting period.  (e.g. a change in running copies)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "sum by (job) (up {job!=\"Metadata-Cache\"})  ",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Service up history",
     "type": "state-timeline",
     "description": "Helps to identify service \"up\" anomalies during the reporting period.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum  by (job) (up{job!=\"Metadata-Cache\"})",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Message-Queue Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Rabbit Memory Usage (%MEM)",
     "type": "table",
     "description": "Calculates the memory usage of the rabbit service  on  per node basis.  Red indicates 80% -  could mean that Rabbit memory usage is getting close to its watermark. ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rabbitmq_process_resident_memory_bytes/rabbitmq_resident_memory_limit_bytes",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "RabbitMQ Memory Usage (per Node)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rabbitmq_process_resident_memory_bytes/rabbitmq_resident_memory_limit_bytes",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}