{
 "title": "HCP for Cloud Scale - Dashboard 7: Encryption Activity",
 "tags": [ "cloudscale" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ClusterName", "label": "Choose  Cluster", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   { "name": "allnodes", "label": "WildCard", "query": ".*" },
   { "name": "excl_net", "label": "Exclude_Device", "query": "^docker.*$|^lo$" }
  ]
 },
 "panels": [
  {
   "title": "System Encryption Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Encrypted Objects",
   "type": "stat",
   "description": "Displays the percentage of encrypted Objects, system wide",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*(sum(metadata_clientobject_active_encrypted_count))/(sum(metadata_clientobject_active_unencrypted_count)+sum(metadata_clientobject_active_encrypted_count))\r\n",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Total Un-Encrypted Objects",
   "type": "stat",
   "description": "The total number of un-encrypted objects",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metadata_clientobject_active_unencrypted_count)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "External KMS Health",
   "type": "stat",
   "description": "Checks the Health of the EXTERNAL KMS (Key Management Server) - e.g all are online",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(0.1+sum(kmip_servers_online)) / (sum(kmip_servers_online) + sum(kmip_servers_offline))"
    }
   ]
  },
  {
   "title": "Admin Initiated Rekey",
   "type": "stat",
   "description": "Total number of re-keys initiated on the system.  Each Rekey will replace the Active KEKs stored in the primary KMS. ",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lifecycle_policy_rekey_initiated_count_total{job=\"MAPI-Gateway\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KEKs per Server",
   "type": "table",
   "description": "Displays the number of KEK (Key encryption Keys) stored in each Key Management Server.  The table is updated once per hour.",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "kmip_total_kek_count",
     "legendFormat": "KMS Name: \"{{kms}}\""
    }
   ]
  },
  {
   "title": "DLS: Rekey policy",
   "type": "stat",
   "description": "Checks whether DLS (Data-Lifecycle Service) is examining objects for REKEY policy. UNHEALTHY indicates that no activity was detected in the last 24 hours.",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(lifecycle_policy_rekey_examine_latency_seconds_count[1h]))"
    }
   ]
  },
  {
   "title": "Total DEKs Re-Encrypted",
   "type": "stat",
   "description": "Total number DEKs that were re-encrypted",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(lifecycle_policy_rekeyed_objects_count_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Encrypted Objects",
   "type": "stat",
   "description": "The total number of encrypted objects",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metadata_clientobject_active_encrypted_count)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Total KEKs",
   "type": "stat",
   "description": "Total number of KEKs (Key Encryption Keys) defined in all KMS.  There is at least one KEK version for each storage component.  Each re-key event will create a new KEK version for each storage component.",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kmip_total_kek_count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DLS service jobs",
   "type": "stat",
   "description": "Total number DLS (data lifecycle Service) jobs running on the system",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (up{job=\"Data-Lifecycle\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Rekey Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Admin Initiated Rekey",
     "type": "state-timeline",
     "description": "(REKEY#) = Marks an Initiate Rekey Event.\n(SCAN#) = Marks the beginning of a new Lifecycle scan.  Each new Session will run until completion.  Checked once every hour",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "sum(lifecycle_policy_started_total{policy=\"DELETE_BACKEND_OBJECTS\"}) % 24",
       "legendFormat": "Scan#"
      },
      {
       "expr": "sum(lifecycle_policy_rekey_initiated_count_total) % 1000",
       "legendFormat": "Rekey#"
      }
     ]
    },
    {
     "title": "Rekey: Object Examination Rate",
     "type": "timeseries",
     "description": "Shows  the rate at which DEKs (Data Encryption Keys) examined, old DEKs found, and DEKs re-encrypted per second.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(lifecycle_policy_rekey_examine_latency_seconds_count[1m]))",
       "legendFormat": "Examined Rate"
      },
      {
       "expr": "sum(rate(lifecycle_policy_rekey_accept_latency_seconds_count[1m]))",
       "legendFormat": "Found"
      },
      {
       "expr": "sum(rate(lifecycle_policy_rekeyed_objects_count_total[1m]))",
       "legendFormat": "Re-encrypted Rate"
      }
     ]
    },
    {
     "title": "Rekey: Latency (Histogram)",
     "type": "barchart",
     "description": "Stacked histogram shows time spent examining DEKs for re-key decision. (latency) ",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "abs(sum(irate(lifecycle_policy_rekey_examine_latency_seconds_bucket{le=\"0.001\"}[1m])) -sum(irate(lifecycle_policy_rekey_examine_latency_seconds_bucket{le=\"0.01\"}[1m])))",
       "legendFormat": ">1ms"
      },
      {
       "expr": "abs(sum(irate(lifecycle_policy_rekey_examine_latency_seconds_bucket{le=\"0.01\"}[1m])) -sum(irate(lifecycle_policy_rekey_examine_latency_seconds_bucket{le=\"0.1\"}[1m])))",
       "legendFormat": ">10ms"
      },
      {
       "expr": "abs(sum(irate(lifecycle_policy_rekey_examine_latency_seconds_bucket{le=\"0.1\"}[1m])) -sum(irate(lifecycle_policy_rekey_examine_latency_seconds_bucket{le=\"100.0\"}[1m])))",
       "legendFormat": ">100ms"
      }
     ]
    }
   ]
  },
  {
   "title": "Rekey Activity By Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rekey: DEK Examination Rate (by Node)",
     "type": "timeseries",
     "description": "The number of DEKs Examined by each node instance ",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(lifecycle_policy_rekey_examine_latency_seconds_count[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Rekey: DEK Re-Encryption Rate (by Node)",
     "type": "timeseries",
     "description": "The number of re-encrypted DEKs by each node instance",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(lifecycle_policy_rekeyed_objects_count_total[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "S3 System Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "S3 IOPS by Operation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (operation) (rate(http_s3_servlet_operations_total{operation=\"S3GetObjectOperation\"}[30s]))",
       "legendFormat": "GET"
      },
      {
       "expr": "sum by (operation) (rate(http_s3_servlet_operations_total{operation=\"S3DeleteObjectOperation\"}[30s]))",
       "legendFormat": "DEL"
      },
      {
       "expr": "sum by (operation) (rate(http_s3_servlet_operations_total{operation=\"S3ListObjectsOperation\"}[30s]))",
       "legendFormat": "LIST"
      },
      {
       "expr": "sum by (operation) (rate(http_s3_servlet_operations_total{operation=\"S3PutObjectOperation\"}[30s]))",
       "legendFormat": "PUT"
      },
      {
       "expr": "sum by (operation) (rate(http_s3_servlet_operations_total{operation=\"S3HeadObjectOperation\"}[30s]))",
       "legendFormat": "HEAD"
      },
      {
       "expr": "sum by (operation) (rate(http_s3_servlet_operations_total{operation=\"S3BulkDeleteObjectOperation\"}[30s]))",
       "legendFormat": "BulkDelete"
      },
      {
       "expr": "sum by (operation) (rate(http_s3_servlet_operations_total{operation=\"S3PutObjectPartOperation\"}[30s]))",
       "legendFormat": "PutPart"
      },
      {
       "expr": "sum by (operation) (rate(http_s3_servlet_operations_total{operation=\"S3ListVersionsOperation\"}[30s]))",
       "legendFormat": "ListVer"
      }
     ]
    },
    {
     "title": "S3 Latency by Operation",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (operation) (rate(http_s3_servlet_requests_latency_seconds_sum{operation=~\"S3BulkDeleteObjectOperation|S3GetObjectOperation|S3PutObjectOperation|S3ListVersionsOperation|S3ListObjectsOperation|S3ListUploadedPartsOperation|S3PutObjectPartOperation\"}[30s]))/sum by (operation) (rate(http_s3_servlet_requests_latency_seconds_count[30s]))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "S3 Throughput by Operation",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(http_s3_servlet_put_object_part_bytes_total{}[30s]))",
       "legendFormat": "PUT-PART"
      },
      {
       "expr": "sum(rate(http_s3_servlet_put_object_bytes_total{}[30s]))",
       "legendFormat": "PUT"
      },
      {
       "expr": "sum(rate(http_s3_servlet_post_object_bytes_total{}[30s]))",
       "legendFormat": "POST"
      },
      {
       "expr": "sum(rate(http_s3_servlet_get_object_response_bytes_total[30s]))",
       "legendFormat": "GET"
      }
     ]
    },
    {
     "title": "Delete Backend Objects Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 56 },
     "targets": [
      {
       "expr": "sum(rate(lifecycle_policy_completed{policy=\"DELETE_BACKEND_OBJECTS\"}[30s]))",
       "legendFormat": "DELETED backend objects"
      },
      {
       "expr": "sum(rate(lifecycle_policy_completed_total{policy=\"DELETE_BACKEND_OBJECTS\"}[30s]))",
       "legendFormat": "DELETED backend objects"
      }
     ]
    }
   ]
  }
 ]
}