{
 "title": "HCP for Cloud Scale - Dashboard 5: System Capacity",
 "tags": [ "cloudscale" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ClusterName", "label": "Choose  Cluster", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   { "name": "allnodes", "label": "WildCard", "query": ".*" },
   { "name": "excl_net", "label": "Exclude_Device", "query": "^docker.*$|^lo$" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "System Capacity and Object Count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cloud Scale Object Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metadata_clientobject_active_count)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Cloud Scale Object and Parts Count",
   "type": "stat",
   "description": "Cloud Scale stores object parts on S-nodes as separate objects.\nThis counter also includes special small objects (DEKs) created on S-nodes as a result of encryption rekey process, if any.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metadata_clientobject_part_active_count)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "S-node Total Object Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "storage_total_objects{store=\"aggregate\"}",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Cloud Scale Object Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(metadata_clientobject_active_count)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Cloud Scale Objects and Parts count",
   "type": "timeseries",
   "description": "Cloud Scale stores object parts on S-nodes as separate objects.\nThis counter also includes special small objects (DEKs) created on S-nodes as a result of encryption rekey process, if any.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(metadata_clientobject_part_active_count OR on() vector(0)) + sum(lifecycle_policy_rekey_accept_latency_seconds_count OR on() vector(0)) ",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total S-nodes Objects count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "storage_total_objects{store=\"aggregate\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Backlog of Undeleted Objects/Parts on S-nodes.",
   "type": "stat",
   "description": "The number of objects/parts to be deleted on S-nodes. It's NOT the same as the number of client objects to be deleted if S3 multipart upload is used.\nIt's the number of objects/parts to be deleted on S-nodes.\nIt also includes small objects (DEKs) created on S-nodes as a result encryption rekey process, if any.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(storage_total_objects{store=\"aggregate\"}) - sum(metadata_clientobject_part_active_count)) * (count(sum(lifecycle_policy_rekey_initiated_count_total OR on() vector(0)) ==0) + (count(sum(lifecycle_policy_rekey_initiated_count_total) > 1) OR on() vector(0)) )"
    }
   ]
  },
  {
   "title": "Cloud Scale Used Capacity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metadata_total_bytes_per_bucket)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "S-node Total Used Capacity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "storage_used_capacity_bytes{store=\"aggregate\"}",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Backlog of Undeleted Objects/Parts on S-nodes",
   "type": "gauge",
   "description": "The number of objects/parts to be deleted on S-nodes. It's NOT the same as the number of client objects to be deleted if S3 multipart upload is used.\nIt's the number of objects/parts to be deleted on S-nodes.\n",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(storage_total_objects{store=\"aggregate\"}) - sum(metadata_clientobject_part_active_count)) * (count(sum(lifecycle_policy_rekey_initiated_count_total OR on() vector(0)) ==0) + (count(sum(lifecycle_policy_rekey_initiated_count_total) > 1) OR on() vector(0)) ) / sum(storage_total_objects{store=\"aggregate\"})"
    }
   ]
  },
  {
   "title": "Total S3 Versioned Delete requests",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_s3_servlet_delete_requests_per_bucket_total{delete_type=\"versioned\"})"
    }
   ]
  },
  {
   "title": "S-node Object Count breakdown",
   "type": "table",
   "description": "Table of capacity by S-node",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "storage_total_objects{store!=\"aggregate\"}",
     "legendFormat": "{{store}}"
    }
   ]
  },
  {
   "title": "Undeleted Objects/Parts Backlog",
   "type": "timeseries",
   "description": "Storage Objects/Parts to be deleted ",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(100* sum(storage_total_objects{store=\"aggregate\"}) - sum(metadata_clientobject_part_active_count)) * (count(sum(lifecycle_policy_rekey_initiated_count_total OR on() vector(0)) ==0) + (count(sum(lifecycle_policy_rekey_initiated_count_total) > 1) OR on() vector(0)) ) / sum(storage_total_objects{store=\"aggregate\"})",
     "legendFormat": "Undeleted objects"
    }
   ]
  },
  {
   "title": "Total S3 Unversioned Delete requests",
   "type": "gauge",
   "description": "The number of S3 Object Delete (unversioned/latest) requests",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_s3_servlet_delete_requests_per_bucket_total{delete_type=\"latest\"})"
    }
   ]
  },
  {
   "title": "S-node Used Capacity breakdown",
   "type": "table",
   "description": "Table of capacity by S-node",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "storage_used_capacity_bytes{store!=\"aggregate\"}/storage_total_capacity_bytes{store!=\"aggregate\"}",
     "legendFormat": "{{store}}"
    }
   ]
  },
  {
   "title": "Metadata Capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Metadata Capacity by Node",
     "type": "table",
     "description": "Metadata Capacity by Node",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "(metadata_used_capacity_bytes)", "legendFormat": "{{store}}" },
      {
       "expr": "(metadata_used_capacity_bytes+metadata_available_capacity_bytes)",
       "legendFormat": "{{store}}"
      },
      {
       "expr": "100*(metadata_used_capacity_bytes/(metadata_used_capacity_bytes+metadata_available_capacity_bytes))",
       "legendFormat": "{{store}}"
      }
     ]
    },
    {
     "title": "Highest Metadata Space Utilization",
     "type": "stat",
     "description": "Highest Metadata space consumed on a local drive ",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(100*metadata_used_capacity_bytes{store!=\"aggregate\"}/(metadata_used_capacity_bytes{store!=\"aggregate\"}+metadata_available_capacity_bytes{store!=\"aggregate\"}))",
       "legendFormat": "{{store}}"
      }
     ]
    },
    {
     "title": "Metadata Space Utilization by node",
     "type": "timeseries",
     "description": "Metadata space consumed on a local drive on each node",
     "gridPos": { "h": 8, "w": 18, "x": 5, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100*metadata_used_capacity_bytes{store!=\"aggregate\"}/(metadata_used_capacity_bytes{store!=\"aggregate\"}+metadata_available_capacity_bytes{store!=\"aggregate\"})",
       "legendFormat": "{{store}}"
      }
     ]
    },
    {
     "title": "Max Metadata Space Utilization ",
     "type": "stat",
     "description": "Max Metadata space consumed on a node ",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(metadata_used_capacity_bytes{store!=\"aggregate\"})"
      }
     ]
    },
    {
     "title": "Metadata Space Utilization by node",
     "type": "timeseries",
     "description": "Metadata space consumed on a local drive on each node (in GB/TB)",
     "gridPos": { "h": 8, "w": 18, "x": 5, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "metadata_used_capacity_bytes{store!=\"aggregate\"}",
       "legendFormat": "{{store}}"
      }
     ]
    },
    {
     "title": "Total Metadata Space Utilization ",
     "type": "stat",
     "description": "Max Metadata space consumed on a node ",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(mcs_disk_usage_per_instance)"
      }
     ]
    },
    {
     "title": "Metadata Space Utilization across all nodes",
     "type": "timeseries",
     "description": "Metadata space consumed on a local drive on each node (in GB/TB)",
     "gridPos": { "h": 8, "w": 18, "x": 5, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "mcs_disk_usage_per_instance", "legendFormat": "{{metadataInstanceId}}" }
     ]
    }
   ]
  },
  {
   "title": "S-node Detailed Capacity Reports",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "S-node Available Capacity",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (store) (storage_available_capacity_bytes{store!=\"aggregate\"})",
       "legendFormat": "AVAIL"
      },
      {
       "expr": "sum by (store) (storage_used_capacity_bytes{store!=\"aggregate\"})",
       "legendFormat": "USED"
      },
      {
       "expr": "sum by (store) (storage_total_capacity_bytes{store!=\"aggregate\"})",
       "legendFormat": "TOTAL"
      }
     ]
    },
    {
     "title": "S-node Object Count",
     "type": "table",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "storage_total_objects{store!=\"aggregate\"}",
       "legendFormat": "{{store}}"
      }
     ]
    },
    {
     "title": "S-node Object Count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 19, "x": 5, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "storage_total_objects{store!=\"aggregate\"}",
       "legendFormat": "{{store}}"
      }
     ]
    },
    {
     "title": "S-node Used Capacity",
     "type": "table",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "storage_used_capacity_bytes{store!=\"aggregate\"}",
       "legendFormat": "{{store}}"
      }
     ]
    },
    {
     "title": "S-node Used Capacity",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 19, "x": 5, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "storage_used_capacity_bytes{store!=\"aggregate\"}",
       "legendFormat": "{{store}}"
      }
     ]
    },
    {
     "title": "S-node Available Capacity",
     "type": "table",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "storage_available_capacity_bytes{store!=\"aggregate\"}",
       "legendFormat": "{{store}}"
      }
     ]
    },
    {
     "title": "S-node Available Capacity",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 19, "x": 5, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "storage_available_capacity_bytes{store!=\"aggregate\"}",
       "legendFormat": "{{store}}"
      }
     ]
    },
    {
     "title": "S-node Capacity Utilization",
     "type": "table",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "storage_used_capacity_bytes{store!=\"aggregate\"}/storage_total_capacity_bytes{store!=\"aggregate\"}",
       "legendFormat": "{{store}}"
      }
     ]
    },
    {
     "title": "S-node Capacity Utilization (%)",
     "type": "timeseries",
     "description": "Table of capacity by S-node",
     "gridPos": { "h": 7, "w": 19, "x": 5, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "storage_used_capacity_bytes{store!=\"aggregate\"}/storage_total_capacity_bytes{store!=\"aggregate\"}",
       "legendFormat": "{{store}}"
      }
     ]
    }
   ]
  }
 ]
}