{
 "title": "HCP for Cloud Scale - Dashboard 1: System Health",
 "tags": [ "cloudscale" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "ClusterName", "label": "Choose  Cluster", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   { "name": "allnodes", "label": "WildCard", "query": ".*" },
   { "name": "excl_net", "label": "Exclude_Device", "query": "^docker.*$|^lo$" }
  ]
 },
 "panels": [
  {
   "title": "System Health Dashboard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Service Uptime Status",
   "type": "stat",
   "description": "Helps to identify service \"up\" anomalies during the reporting period.  (e.g. a change in running copies)",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "changeCount" ] } },
   "targets": [
    {
     "expr": "sum by (job)  (up unless {job=\"Metadata-Cache\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Database Partitions Per Node",
   "type": "stat",
   "description": "The largest number of partitions in a node. ",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(mcs_partitions_per_instance)"
    }
   ]
  },
  {
   "title": "Metadata Space Used / Available",
   "type": "piechart",
   "description": "Ratio of Average number of objects per partition vs max number of objects in any ONE partitions",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (sum by (instance) (metadata_used_capacity_bytes{}))",
     "legendFormat": "USED"
    },
    {
     "expr": "sum (sum by (instance) (metadata_available_capacity_bytes{}))",
     "legendFormat": "AVAIL"
    }
   ]
  },
  {
   "title": "S-node Capacity Used / Available",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(storage_used_capacity_bytes{store=\"aggregate\"})",
     "legendFormat": "USED"
    },
    {
     "expr": "sum(storage_available_capacity_bytes{store=\"aggregate\"})",
     "legendFormat": "AVAIL"
    }
   ]
  },
  {
   "title": "Undeleted objects backlog",
   "type": "stat",
   "description": "The undeleted objects backlog is high (over 1 Billion objects). Check Dashboard 6 - Data Lifecycle - DELETE_BACKEND_OBJECTS policy. Read HCP for Cloud Scale Administrator Guide for more details.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(storage_total_objects{store=\"aggregate\"}) - sum(metadata_clientobject_part_active_count)) * (count(sum(lifecycle_policy_rekey_initiated_count_total OR on() vector(0)) ==0) + (count(sum(lifecycle_policy_rekey_initiated_count_total) > 1) OR on() vector(0)) )"
    }
   ]
  },
  {
   "title": "Bucket Expiration Lifecycle Considerations",
   "type": "stat",
   "description": "Checks if you should consider Bucket Expiration Lifecycle policy. ",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(http_s3_servlet_delete_requests_per_bucket_total{delete_type=\"latest\"})"
    }
   ]
  },
  {
   "title": "Database Partitions Protection",
   "type": "stat",
   "description": "This panel shows the DB partitions protection level: Healthy, Degraded, Unprotected (Failures Detected),  and Overprotected. \nRead HCP for Cloud Scale Administrator Guide for more details.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((count(count(mcs_copies_per_partition==1) > 0) OR on() vector(0)) * 1000) + ((count(count(mcs_copies_per_partition==2) > 0) OR on() vector(0)) * 100) + ((count(count(mcs_copies_per_partition==3) > 0) OR on() vector(0)) * 1) + ((count(count(mcs_copies_per_partition==0) > 0) OR on() vector(0)) * 2) + ((count(count(mcs_copies_per_partition==4) > 0) OR on() vector(0)) * 10)"
    }
   ]
  },
  {
   "title": "Used Metadata Capacity (%)",
   "type": "table",
   "description": "Used Metadata Capacity by Node",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*(metadata_used_capacity_bytes/(metadata_used_capacity_bytes+metadata_available_capacity_bytes))",
     "legendFormat": "{{store}}"
    }
   ]
  },
  {
   "title": "Used S-node Capacity (by Node)",
   "type": "table",
   "description": "Table of capacity by S-node",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*(storage_used_capacity_bytes{store!=\"aggregate\"}/storage_total_capacity_bytes{store!=\"aggregate\"})",
     "legendFormat": "{{store}}"
    }
   ]
  },
  {
   "title": "Encrypted Objects",
   "type": "stat",
   "description": "Displays the percentage of encrypted Objects, system wide",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*(sum(metadata_clientobject_active_encrypted_count))/(sum(metadata_clientobject_active_unencrypted_count)+sum(metadata_clientobject_active_encrypted_count))\r\n",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "DLS: Delete Backend Objects policy",
   "type": "stat",
   "description": "Checks whether DLS (Data-Lifecycle Service) is examining objects for DELETE_BACKEND_OBJECTS policy. UNHEALTHY indicates that no activity was detected in the last 24 hours.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(lifecycle_policy_examine_latency_seconds_count{policy=\"DELETE_BACKEND_OBJECTS\"}[2h]))"
    }
   ]
  },
  {
   "title": "DLS: Version Expiration policy",
   "type": "stat",
   "description": "Checks whether DLS (Data-Lifecycle Service) is examining objects for VERSION_EXPIRATION policy. UNHEALTHY indicates that no activity was detected in the last 24 hours.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(lifecycle_policy_examine_latency_seconds_count{policy=\"VERSION_EXPIRATION\"}[2h]))"
    }
   ]
  },
  {
   "title": "DLS: Tombstone Delete policy",
   "type": "stat",
   "description": "Checks whether DLS (Data-Lifecycle Service) is examining objects for TOMBSTONE_DELETION policy",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(lifecycle_policy_examine_latency_seconds_count{policy=\"TOMBSTONE_DELETION\"}) - sum(lifecycle_policy_examine_latency_seconds_count{policy=\"TOMBSTONE_DELETION\"} offset 24h)"
    }
   ]
  },
  {
   "title": "DLS: Incomplete MPU expiration policy",
   "type": "stat",
   "description": "Checks whether DLS (Data-Lifecycle Service) is examining objects for INCOMPLETE_MPU_EXPIRATION policy",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(lifecycle_policy_examine_latency_seconds_count{policy=\"INCOMPLETE_MPU_EXPIRATION \"}) - sum(lifecycle_policy_examine_latency_seconds_count{policy=\"TOMBSTONE_DELETION\"} offset 24h)"
    }
   ]
  },
  {
   "title": "DLS: Chargeback policy",
   "type": "stat",
   "description": "Checks whether DLS (Data-Lifecycle Service) is examining objects for CHARGEBACK_POPULATION policy",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(delta(lifecycle_policy_examine_latency_seconds_count{policy=\"CHARGEBACK_POPULATION\"}[24h])))"
    }
   ]
  },
  {
   "title": "External KMS Health",
   "type": "stat",
   "description": "Checks the Health of the EXTERNAL KMS (Key Management Server) - e.g all are online",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(0.1+sum(kmip_servers_online)) / (sum(kmip_servers_online) + sum(kmip_servers_offline))"
    }
   ]
  },
  {
   "title": "S3 I/O Balance",
   "type": "stat",
   "description": "S3 I/O should be distributed evenly among nodes. Any value >15% imbalance should be investigated.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100* abs ((max ( sum by (instance) (http_s3_servlet_operations_total{job=\"S3-Gateway\"})) - min ( sum by (instance) (http_s3_servlet_operations_total{job=\"S3-Gateway\"}))) / avg ( sum by (instance) (http_s3_servlet_operations_total{job=\"S3-Gateway\"}))) ",
     "legendFormat": "Unbalance"
    }
   ]
  },
  {
   "title": "Metadata Partition Balance",
   "type": "stat",
   "description": "A Database should be distributed evenly among nodes. Any node showing >15% imbalance should be investigated.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100* abs ((max (mcs_partitions_per_instance) - min (mcs_partitions_per_instance)) / avg (mcs_partitions_per_instance)) ",
     "legendFormat": "Unbalance"
    }
   ]
  },
  {
   "title": "Metadata Error Mode Status",
   "type": "stat",
   "description": "Indicate if any database instance has entered error mode, resulting in a loss of availability. Contact Hitachi support if this panel displays anything other than \"Normal\".",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(myrtle_updates_rejected_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DLS: Rekey policy",
   "type": "stat",
   "description": "Checks whether DLS (Data-Lifecycle Service) is examining objects for REKEY policy. UNHEALTHY indicates that no activity was detected in the last 24 hours.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(lifecycle_policy_rekey_examine_latency_seconds_count[1h]))"
    }
   ]
  }
 ]
}