{
 "title": "HCP for Cloud Scale - Dashboard 4: Buckets Stats and Activity",
 "tags": [ "cloudscale" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ClusterName", "label": "Choose  Cluster", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   { "name": "allnodes", "label": "WildCard", "query": "${VAR_ALLNODES}" },
   { "name": "excl_net", "label": "Exclude_Device", "query": "^docker.*$|^lo$" }
  ]
 },
 "panels": [
  {
   "title": "Bucket Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Buckets",
   "type": "stat",
   "description": "Total number of buckets existing on the system",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (bucket)(metadata_total_objects_per_bucket{})",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Current Stats per bucket",
   "type": "table",
   "gridPos": { "h": 14, "w": 21, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (bucket)(metadata_total_bytes_per_bucket{})",
     "legendFormat": "{{bucket}}"
    },
    {
     "expr": "sum by (bucket)(metadata_total_objects_per_bucket{})",
     "legendFormat": "{{bucket}}"
    },
    {
     "expr": "sum by (bucket)(metadata_total_bytes_per_bucket{}) / sum by (bucket)(metadata_total_objects_per_bucket{})",
     "legendFormat": "{{bucket}}"
    },
    {
     "expr": "(sum by (bucket)(metadata_total_objects_per_bucket{})) -  (sum by (bucket)(metadata_total_objects_per_bucket{} offset 24h))",
     "legendFormat": "{{bucket}}"
    },
    {
     "expr": "(sum by (bucket)(metadata_total_bytes_per_bucket{})) -  (sum by (bucket)(metadata_total_bytes_per_bucket{} offset 24h))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "New Buckets",
   "type": "stat",
   "description": "Which buckets were created during reporting period",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (bucket)(http_s3_servlet_requests_per_bucket{operation=\"S3CreateBucketOperation\"})"
    }
   ]
  },
  {
   "title": "Small Buckets",
   "type": "stat",
   "description": "The number of small buckets: less than 100 objects and less that 1GB",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count ((sum by (bucket) (metadata_total_objects_per_bucket) <= 100) and (sum by (bucket) (metadata_total_bytes_per_bucket) <= 1000000000))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Bucket Expiration Lifecycle policy considerations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "Buckets with unversioned deletes",
   "type": "stat",
   "description": "Total number of buckets that received unversioned deletes, and thus, very likely need Bucket Expiration Lifecycle policy.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (bucket)(http_s3_servlet_delete_requests_per_bucket_total{delete_type=\"latest\"})",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Buckets with versioned deletes",
   "type": "stat",
   "description": "Total number of buckets that received versioned deletes.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (bucket)(http_s3_servlet_delete_requests_per_bucket_total{delete_type=\"versioned\"})",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Number of buckets that likely need Expiration Lifecycle policy",
   "type": "stat",
   "description": "The number of buckets where the number of unversioned deletes is above 1000",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count by (bucket)(http_s3_servlet_delete_requests_per_bucket_total{delete_type=\"latest\"} > 1000))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Versioned and Unversioned Deletes",
   "type": "table",
   "description": "The number of versioned and unversioned deletes per bucket.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (bucket)(http_s3_servlet_delete_requests_per_bucket_total{delete_type=\"versioned\"})",
     "legendFormat": "{{bucket}}"
    },
    {
     "expr": "sum by (bucket)(http_s3_servlet_delete_requests_per_bucket_total{delete_type=\"latest\"})",
     "legendFormat": "{{bucket}}"
    },
    {
     "expr": "sum by (bucket)(rate(http_s3_servlet_delete_requests_per_bucket_total[10m]))",
     "legendFormat": "{{bucket}}"
    },
    {
     "expr": "sum by (bucket)(http_s3_servlet_delete_requests_per_bucket_total{delete_type=\"latest\"})",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Bucket I/O Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Bucket with Max PUT Throughput ",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(1,sum by (bucket) (rate(http_s3_servlet_ingest_object_bytes_per_bucket_total[10m])))",
       "legendFormat": "{{bucket}}"
      },
      {
       "expr": "topk(1,sum by (bucket) (rate(http_s3_servlet_ingest_object_bytes_per_bucket[10m])))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Bucket with Max GET Throughput ",
     "type": "stat",
     "description": "A bucket with Max GET Throughput ",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(1,sum by (bucket) (rate(http_s3_servlet_get_object_response_bytes_per_bucket_total[10m])))",
       "legendFormat": "{{bucket}}"
      },
      {
       "expr": "topk(1,sum by (bucket) (rate(http_s3_servlet_get_object_response_bytes_per_bucket[10m])))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "S3 PUT/GET Throughput by bucket",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "topk(3,sum by (bucket) (rate(http_s3_servlet_get_object_response_bytes_per_bucket_total[30s])))",
       "legendFormat": "GET:{{bucket}}"
      },
      {
       "expr": "topk(3,sum by (bucket) (rate(http_s3_servlet_ingest_object_bytes_per_bucket_total[30s])))",
       "legendFormat": "Ingest:{{bucket}}"
      },
      {
       "expr": "topk(3,sum by (bucket) (rate(http_s3_servlet_get_object_response_bytes_per_bucket[30s])))",
       "legendFormat": "GET:{{bucket}}"
      },
      {
       "expr": "topk(3,sum by (bucket) (rate(http_s3_servlet_ingest_object_bytes_per_bucket[30s])))",
       "legendFormat": "Ingest:{{bucket}}"
      }
     ]
    },
    {
     "title": "Top S3 PUT IOPS by bucket",
     "type": "timeseries",
     "description": "Which buckets are writing",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "topk(3,sum by (bucket)(rate(http_s3_servlet_requests_per_bucket{operation=\"S3PutObjectOperation\"}[30s])))",
       "legendFormat": "{{bucket}}"
      },
      {
       "expr": "topk(1,sum by (bucket)(rate(http_s3_servlet_requests_per_bucket{operation=\"S3PutObjectPartOperation\"}[30s])))",
       "legendFormat": "PutPart {{bucket}}"
      },
      {
       "expr": "topk(3,sum by (bucket)(rate(http_s3_servlet_requests_per_bucket_total{operation=\"S3PutObjectOperation\"}[30s])))",
       "legendFormat": "{{bucket}}"
      },
      {
       "expr": "topk(1,sum by (bucket)(rate(http_s3_servlet_requests_per_bucket_total{operation=\"S3PutObjectPartOperation\"}[30s])))",
       "legendFormat": "PutPart {{bucket}}"
      }
     ]
    },
    {
     "title": "Top S3 PUT Throughput by bucket",
     "type": "timeseries",
     "description": "Max throughput over the reporting period",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "topk(3,sum by (bucket) (rate(http_s3_servlet_ingest_object_bytes_per_bucket[30s])))",
       "legendFormat": "PUT {{bucket}}"
      },
      {
       "expr": "topk(1,sum by (bucket) (rate(http_s3_servlet_get_object_response_bytes_per_bucket[30s])))",
       "legendFormat": "GET {{bucket}}"
      },
      {
       "expr": "topk(3,sum by (bucket) (rate(http_s3_servlet_ingest_object_bytes_per_bucket_total[30s])))",
       "legendFormat": "PUT {{bucket}}"
      },
      {
       "expr": "topk(1,sum by (bucket) (rate(http_s3_servlet_get_object_response_bytes_per_bucket_total[30s])))",
       "legendFormat": "GET {{bucket}}"
      }
     ]
    },
    {
     "title": "Top S3 Delete Activity by bucket",
     "type": "timeseries",
     "description": "Versioned and Unversioned deletes\nsum by (bucket)(http_s3_servlet_delete_requests_per_bucket_total)",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "topk(1,sum by (bucket)(rate(http_s3_servlet_delete_requests_per_bucket_total{}[10m])))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Top S3 List Activity by bucket",
     "type": "timeseries",
     "description": "Which buckets are Listing",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "topk(1,sum by (bucket)(rate(http_s3_servlet_requests_per_bucket{operation=~\"S3List.*Operation\"}[10m])))",
       "legendFormat": "{{bucket}}"
      },
      {
       "expr": "topk(1,sum by (bucket)(rate(http_s3_servlet_requests_per_bucket_total{operation=~\"S3ListVersionsOperation|S3ListObjectsOperation|S3ListObjectsV1Operation|S3ListObjectsV2Operation\"}[10m])))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Top GET Throughput by bucket",
     "type": "timeseries",
     "description": "Max throughput over the reporting period",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "topk(1,sum by (bucket) (rate(http_s3_servlet_get_object_response_bytes_per_bucket_total[10m])))",
       "legendFormat": "GET {{bucket}}"
      },
      {
       "expr": "topk(1,sum by (bucket) (rate(http_s3_servlet_get_object_response_bytes_per_bucket[10m])))",
       "legendFormat": "GET {{bucket}}"
      }
     ]
    },
    {
     "title": "Top S3 GET IOPS by bucket",
     "type": "timeseries",
     "description": "Which buckets are reading",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "topk(1,sum by (bucket)(rate(http_s3_servlet_requests_per_bucket{operation=\"S3GetObjectOperation\"}[1m])))",
       "legendFormat": "{{bucket}}"
      },
      {
       "expr": "topk(1,sum by (bucket)(rate(http_s3_servlet_requests_per_bucket_total{operation=\"S3GetObjectOperation\"}[1m])))",
       "legendFormat": "{{bucket}}"
      }
     ]
    }
   ]
  }
 ]
}