{
 "title": "HCP for Cloud Scale - Dashboard 3: S3 Activity",
 "tags": [ "cloudscale" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ClusterName", "label": "Choose  Cluster", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   { "name": "allnodes", "label": "WildCard", "query": ".*" },
   { "name": "excl_net", "label": "Exclude_Device", "query": "^docker.*$|^lo$" }
  ]
 },
 "panels": [
  {
   "title": "S3 Distribution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "S3 I/O distribution",
     "type": "piechart",
     "description": "Pie chart describing the distribution of S3 requests between HCP-CS nodes (S3 Gateway instances). ",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (instance) (http_s3_servlet_operations_total{job=\"S3-Gateway\"})"
      }
     ]
    },
    {
     "title": "S3 Operations distribution",
     "type": "piechart",
     "description": "S3 Operations distribution:\n* GET : S3GetObjectOperation\n* PUT : S3PutObjectOperation\n* BULK-DELETE : S3BulkDeleteObjectOperation\n* LIST-VERSIONS : S3ListVersionsOperation\n* LIST-OBJECTS : S3ListObjectsOperation\n* LIST-UPLOADED-PARTS : S3ListUploadedPartsOperation\n* PUT-PARTS : S3PutObjectPartOperation",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (operation) (http_s3_servlet_operations_total{operation=~\"S3BulkDeleteObjectOperation|S3GetObjectOperation|S3PutObjectOperation|S3ListVersionsOperation|S3ListObjectsOperation|S3ListUploadedPartsOperation|S3PutObjectPartOperation|S3PostSelectObjectContentOperation\"})",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "S3 Operations distribution",
     "type": "table",
     "description": "S3 Operations distribution:\n* GET : S3GetObjectOperation\n* PUT : S3PutObjectOperation\n* BULK-DELETE : S3BulkDeleteObjectOperation\n* LIST-VERSIONS : S3ListVersionsOperation\n* LIST-OBJECTS : S3ListObjectsOperation\n* LIST-UPLOADED-PARTS : S3ListUploadedPartsOperation\n* PUT-PARTS : S3PutObjectPartOperation",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (operation) (http_s3_servlet_operations_total{operation=~\"S3BulkDeleteObjectOperation|S3GetObjectOperation|S3PutObjectOperation|S3ListVersionsOperation|S3ListObjectsOperation|S3ListUploadedPartsOperation|S3PutObjectPartOperation|S3PostSelectObjectContentOperation\"})",
       "legendFormat": "{{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System Overall S3 Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "S3 Throughput by Operation",
     "type": "timeseries",
     "description": "S3 Throughput by Operation:\n* PUT\n* PUT-PART\n* POST\n* GET",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(http_s3_servlet_put_object_part_bytes_total{}[10m]))",
       "legendFormat": "PUT-PART"
      },
      {
       "expr": "sum(rate(http_s3_servlet_put_object_bytes_total{}[10m]))",
       "legendFormat": "PUT"
      },
      {
       "expr": "sum(rate(http_s3_servlet_post_object_bytes_total{}[10m]))",
       "legendFormat": "POST"
      },
      {
       "expr": "sum(rate(http_s3_servlet_get_object_response_bytes_total[10m]))",
       "legendFormat": "GET"
      }
     ]
    },
    {
     "title": "S3 IOPS by Operation",
     "type": "timeseries",
     "description": "S3 IOPS by Operation:\n* GET\n* DEL\n* PUT\n* HEAD\n* BULK-DELETE\n* PUT-PART\n* LIST-VERSION",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (operation) (rate(http_s3_servlet_operations_total{operation=\"S3GetObjectOperation\"}[10m]))",
       "legendFormat": "GET"
      },
      {
       "expr": "sum by (operation) (rate(http_s3_servlet_operations_total{operation=\"S3DeleteObjectOperation\"}[10m]))",
       "legendFormat": "DEL"
      },
      {
       "expr": "sum by (operation) (rate(http_s3_servlet_operations_total{operation=\"S3ListObjectsOperation\"}[10m]))",
       "legendFormat": "LIST"
      },
      {
       "expr": "sum by (operation) (rate(http_s3_servlet_operations_total{operation=\"S3PutObjectOperation\"}[10m]))",
       "legendFormat": "PUT"
      },
      {
       "expr": "sum by (operation) (rate(http_s3_servlet_operations_total{operation=\"S3HeadObjectOperation\"}[10m]))",
       "legendFormat": "HEAD"
      },
      {
       "expr": "sum by (operation) (rate(http_s3_servlet_operations_total{operation=\"S3BulkDeleteObjectOperation\"}[10m]))",
       "legendFormat": "BULK-DELETE"
      },
      {
       "expr": "sum by (operation) (rate(http_s3_servlet_operations_total{operation=\"S3PutObjectPartOperation\"}[10m]))",
       "legendFormat": "PUT-PART"
      },
      {
       "expr": "sum by (operation) (rate(http_s3_servlet_operations_total{operation=\"S3ListVersionsOperation\"}[10m]))",
       "legendFormat": "LIST-VERSION"
      }
     ]
    },
    {
     "title": "S3 Operations Latency Distribution (counts per second)",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "abs(sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{le=\"0.01\"}[1m])) - sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{le=\"0.1\"}[1m])))",
       "legendFormat": "<100ms"
      },
      {
       "expr": "abs(sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{le=\"0.1\"}[1m])) - sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{le=\"0.5\"}[1m])))",
       "legendFormat": ">100ms"
      },
      {
       "expr": "abs(sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{le=\"0.5\"}[1m])) - sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{le=\"1.0\"}[1m])))",
       "legendFormat": ">500ms"
      },
      {
       "expr": "abs(sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{le=\"1.0\"}[1m])) - sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{le=\"5.0\"}[1m])))",
       "legendFormat": ">1s"
      },
      {
       "expr": "abs(sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{le=\"5.0\"}[1m])) - sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{le=\"10.0\"}[1m])))",
       "legendFormat": ">5s"
      },
      {
       "expr": "abs(sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{le=\"10.0\"}[1m])) - sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{le=\"50.0\"}[1m])))",
       "legendFormat": ">10s"
      },
      {
       "expr": "abs(sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{le=\"50.0\"}[1m])) - sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{le=\"100.0\"}[1m])))",
       "legendFormat": ">50s"
      }
     ]
    },
    {
     "title": "S3 Latency by Operation",
     "type": "timeseries",
     "description": "Latency by S3 Operation: \n* GET \n* PUT\n* BULK-DELETE\n* LIST-VERSIONS\n* LIST-OBEJCTS\n* LIST-UPLOADED-PARTS\n* PUT-PART",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (operation) (rate(http_s3_servlet_requests_latency_seconds_sum{operation=~\"S3BulkDeleteObjectOperation\"}[10m]))/sum by (operation) (rate(http_s3_servlet_requests_latency_seconds_count[10m]))",
       "legendFormat": "BULK-DELETE"
      },
      {
       "expr": "sum by (operation) (rate(http_s3_servlet_requests_latency_seconds_sum{operation=~\"S3GetObjectOperation\"}[10m]))/sum by (operation) (rate(http_s3_servlet_requests_latency_seconds_count[10m]))",
       "legendFormat": "GET"
      },
      {
       "expr": "sum by (operation) (rate(http_s3_servlet_requests_latency_seconds_sum{operation=~\"S3PutObjectOperation\"}[10m]))/sum by (operation) (rate(http_s3_servlet_requests_latency_seconds_count[10m]))",
       "legendFormat": "PUT"
      },
      {
       "expr": "sum by (operation) (rate(http_s3_servlet_requests_latency_seconds_sum{operation=~\"S3ListVersionsOperation\"}[10m]))/sum by (operation) (rate(http_s3_servlet_requests_latency_seconds_count[10m]))",
       "legendFormat": "LIST-VERSIONS"
      },
      {
       "expr": "sum by (operation) (rate(http_s3_servlet_requests_latency_seconds_sum{operation=~\"S3ListObjectsOperation\"}[10m]))/sum by (operation) (rate(http_s3_servlet_requests_latency_seconds_count[10m]))",
       "legendFormat": "LIST-OBJECTS"
      },
      {
       "expr": "sum by (operation) (rate(http_s3_servlet_requests_latency_seconds_sum{operation=~\"S3ListUploadedPartsOperation\"}[10m]))/sum by (operation) (rate(http_s3_servlet_requests_latency_seconds_count[10m]))",
       "legendFormat": "LIST-UPLOADED-PARTS"
      },
      {
       "expr": "sum by (operation) (rate(http_s3_servlet_requests_latency_seconds_sum{operation=~\"S3PutObjectPartOperation\"}[10m]))/sum by (operation) (rate(http_s3_servlet_requests_latency_seconds_count[10m]))",
       "legendFormat": "PUT-PART"
      }
     ]
    },
    {
     "title": "S3 Operation Latency by Node",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "http_s3_servlet_requests_latency_seconds{operation=\"S3PutObjectOperation\"}",
       "legendFormat": "PUT {{instance}}"
      },
      {
       "expr": "http_s3_servlet_requests_latency_seconds{operation=\"S3GetObjectOperation\"}",
       "legendFormat": "GET {{instance}}"
      },
      {
       "expr": "http_s3_servlet_requests_latency_seconds{operation=\"S3DeleteObjectOperation\"}",
       "legendFormat": "DEL {{instance}}"
      }
     ]
    },
    {
     "title": "S3 Operation Latency (max observed)",
     "type": "barchart",
     "description": "The max observed latency on any node over the reporting period",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max(topk(1,(http_s3_servlet_requests_latency_seconds{operation=\"S3PutObjectOperation\"})))",
       "legendFormat": "PUT {{instance}}"
      },
      {
       "expr": "max(topk(1,(http_s3_servlet_requests_latency_seconds{operation=\"S3GetObjectOperation\"})))",
       "legendFormat": "GET {{instance}}"
      },
      {
       "expr": "max(topk(1,(http_s3_servlet_requests_latency_seconds{operation=\"S3DeleteObjectOperation\"})))",
       "legendFormat": "DEL {{instance}}"
      },
      {
       "expr": "max(topk(1,(http_s3_servlet_requests_latency_seconds{operation=\"S3PutObjectPartOperation\"})))",
       "legendFormat": "PutPart{{instance}}"
      },
      {
       "expr": "max(topk(1,(http_s3_servlet_requests_latency_seconds{operation=\"S3BulkDeleteObjectOperation\"})))",
       "legendFormat": "BulkDelete{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System S3 Ingest Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Data Moved (ingested since Power-on)",
     "type": "stat",
     "description": "Volume of Data written and read during reporting period",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(http_s3_servlet_put_object_bytes_total{})",
       "legendFormat": "PUT"
      },
      {
       "expr": "sum(http_s3_servlet_put_object_part_bytes_total{})",
       "legendFormat": "PUT-PARTS"
      },
      {
       "expr": "sum(http_s3_servlet_put_copied_bytes_total{})",
       "legendFormat": "PUT-COPY"
      }
     ]
    },
    {
     "title": "Data Moved (Ingested since power-on)",
     "type": "timeseries",
     "description": "Volume of Data ingested since power-on",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(http_s3_servlet_put_object_bytes_total{})",
       "legendFormat": "PUT"
      },
      {
       "expr": "sum(http_s3_servlet_put_object_part_bytes_total{})",
       "legendFormat": "PUT-PARTS"
      },
      {
       "expr": "sum(http_s3_servlet_put_copied_bytes_total{})",
       "legendFormat": "PUT-COPY"
      }
     ]
    },
    {
     "title": "Data Moved (ingested during period)",
     "type": "stat",
     "description": "Volume of Data written and read during reporting period",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "delta" ] } },
     "targets": [
      {
       "expr": "sum(http_s3_servlet_put_object_bytes_total{})",
       "legendFormat": "PUT"
      },
      {
       "expr": "sum(http_s3_servlet_put_object_part_bytes_total{})",
       "legendFormat": "PUT-PARTS"
      },
      {
       "expr": "sum(http_s3_servlet_put_copied_bytes_total{})",
       "legendFormat": "PUT-COPY"
      }
     ]
    },
    {
     "title": "S3 Ingest Max Throughput",
     "type": "stat",
     "description": "Max throughput during reporting period",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "sum(rate(http_s3_servlet_put_object_bytes_total{}[10m]))",
       "legendFormat": "PUT"
      },
      {
       "expr": "sum(rate(http_s3_servlet_put_object_part_bytes_total{}[10m]))",
       "legendFormat": "PUT-PARTS"
      },
      {
       "expr": "sum(rate(http_s3_servlet_put_copied_bytes_total{}[10m]))",
       "legendFormat": "PUT-COPY"
      }
     ]
    },
    {
     "title": "Max S3 PUT Latency ",
     "type": "stat",
     "gridPos": { "h": 10, "w": 4, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "abs(sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3PutObjectOperation\", le=\"0.1\"}[1m])) - sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3PutObjectOperation\", le=\"0.5\"}[1m])))",
       "legendFormat": ">100ms"
      },
      {
       "expr": "abs(sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3PutObjectOperation\", le=\"0.5\"}[1m])) - sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3PutObjectOperation\", le=\"1.0\"}[1m])))",
       "legendFormat": ">500ms"
      },
      {
       "expr": "abs(sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3PutObjectOperation\", le=\"1.0\"}[1m])) - sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3PutObjectOperation\", le=\"5.0\"}[1m])))",
       "legendFormat": ">1s"
      },
      {
       "expr": "abs(sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3PutObjectOperation\", le=\"5.0\"}[1m])) - sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3PutObjectOperation\", le=\"10.0\"}[1m])))",
       "legendFormat": ">5s"
      },
      {
       "expr": "abs(sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3PutObjectOperation\", le=\"10.0\"}[1m])) - sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3PutObjectOperation\", le=\"50.0\"}[1m])))",
       "legendFormat": ">10s"
      },
      {
       "expr": "abs(sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3PutObjectOperation\", le=\"50.0\"}[1m])) - sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3PutObjectOperation\", le=\"100.0\"}[1m])))",
       "legendFormat": ">50s"
      }
     ]
    },
    {
     "title": "S3 PUT Latency Distribution (counts per second)",
     "type": "barchart",
     "gridPos": { "h": 10, "w": 20, "x": 4, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "abs(sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3PutObjectOperation\", le=\"0.1\"}[1m])) - sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3PutObjectOperation\", le=\"0.5\"}[1m])))",
       "legendFormat": ">100ms"
      },
      {
       "expr": "abs(sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3PutObjectOperation\", le=\"0.5\"}[1m])) - sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3PutObjectOperation\", le=\"1.0\"}[1m])))",
       "legendFormat": ">500ms"
      },
      {
       "expr": "abs(sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3PutObjectOperation\", le=\"1.0\"}[1m])) - sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3PutObjectOperation\", le=\"5.0\"}[1m])))",
       "legendFormat": ">1s"
      },
      {
       "expr": "abs(sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3PutObjectOperation\", le=\"5.0\"}[1m])) - sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3PutObjectOperation\", le=\"10.0\"}[1m])))",
       "legendFormat": ">5s"
      },
      {
       "expr": "abs(sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3PutObjectOperation\", le=\"10.0\"}[1m])) - sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3PutObjectOperation\", le=\"50.0\"}[1m])))",
       "legendFormat": ">10s"
      },
      {
       "expr": "abs(sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3PutObjectOperation\", le=\"50.0\"}[1m])) - sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3PutObjectOperation\", le=\"100.0\"}[1m])))",
       "legendFormat": ">50s"
      }
     ]
    },
    {
     "title": "S3 Ingest Max Latency",
     "type": "stat",
     "description": "Ingest Latency during reporting period",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max(http_s3_servlet_requests_latency_seconds{operation=\"S3PutObjectOperation\"})",
       "legendFormat": "PUT"
      },
      {
       "expr": "max(http_s3_servlet_requests_latency_seconds{operation=\"S3PutObjectPartOperation\"})",
       "legendFormat": "PUT-PARTS"
      },
      {
       "expr": "max(http_s3_servlet_requests_latency_seconds{operation=\"S3PutObjectCopyOperation\"})",
       "legendFormat": "PUT-COPY"
      }
     ]
    },
    {
     "title": "S3 Ingest Latency (detail by node)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 20, "x": 4, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "http_s3_servlet_requests_latency_seconds{operation=\"S3PutObjectOperation\"}",
       "legendFormat": "PUT {{instance}}"
      },
      {
       "expr": "http_s3_servlet_requests_latency_seconds{operation=\"S3PutObjectPartOperation\"}",
       "legendFormat": "PUT-PART {{instance}}"
      },
      {
       "expr": "http_s3_servlet_requests_latency_seconds{operation=\"S3PutObjectCopyOperation\"}",
       "legendFormat": "PUT-COPY {{instance}}"
      }
     ]
    },
    {
     "title": "S3 Ingest Throughput",
     "type": "stat",
     "description": "Volume of Data written and read during reporting period",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "sum(rate(http_s3_servlet_put_object_bytes_total[1m]))",
       "legendFormat": "PUT"
      },
      {
       "expr": "sum(rate(http_s3_servlet_put_object_part_bytes_total[1m]))",
       "legendFormat": "PUT-PARTS"
      },
      {
       "expr": "sum(rate(http_s3_servlet_put_copied_bytes_total[1m]))",
       "legendFormat": "PUT-COPY"
      }
     ]
    },
    {
     "title": "S3 Ingest Throughput by Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(http_s3_servlet_put_object_bytes_total[10m]))",
       "legendFormat": "PUT Total"
      },
      {
       "expr": "sum(rate(http_s3_servlet_put_object_part_bytes_total[10m]))",
       "legendFormat": "PART total"
      },
      {
       "expr": "rate(http_s3_servlet_put_object_bytes_total[10m])",
       "legendFormat": "PUT {{instance}}"
      },
      {
       "expr": "rate(http_s3_servlet_put_object_part_bytes_total[10m])",
       "legendFormat": "PART {{instance}}"
      },
      {
       "expr": "rate(http_s3_servlet_put_copied_bytes_total[10m])",
       "legendFormat": "PUT-COPY {{instance}}"
      }
     ]
    },
    {
     "title": "S3 Ingest IOPS",
     "type": "stat",
     "description": "IOPS of Data written  during reporting period",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "sum(rate(http_s3_servlet_operations_total{operation=\"S3PutObjectOperation\"}[1m]))",
       "legendFormat": "PUT"
      },
      {
       "expr": "sum(rate(http_s3_servlet_operations_total{operation=\"S3PutObjectPartOperation\"}[1m]))",
       "legendFormat": "PUT-PARTS"
      },
      {
       "expr": "sum(rate(http_s3_servlet_operations_total{operation=\"S3PutObjectCopyOperation\"}[1m]))",
       "legendFormat": "PUT-COPY"
      }
     ]
    },
    {
     "title": "S3 Ingest IOPS by Node",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 20, "x": 4, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum(rate(http_s3_servlet_operations_total{operation=\"S3PutObjectOperation\"}[1m]))",
       "legendFormat": "PUT Total"
      },
      {
       "expr": "sum(rate(http_s3_servlet_operations_total{operation=\"S3PutObjectPartOperation\"}[1m]))",
       "legendFormat": "PART total"
      },
      {
       "expr": "rate(http_s3_servlet_operations_total{operation=\"S3PutObjectOperation\"}[1m])",
       "legendFormat": "PUT {{instance}}"
      },
      {
       "expr": "rate(http_s3_servlet_operations_total{operation=\"S3PutObjectPartOperation\"}[1m])",
       "legendFormat": "PART {{instance}}"
      },
      {
       "expr": "rate(http_s3_servlet_operations_total{operation=\"S3PutObjectCopyOperation\"}[1m])",
       "legendFormat": "PUT-COPY {{instance}}"
      },
      {
       "expr": "sum(rate(http_s3_servlet_operations_total{operation=\"S3PutCopyObjectOperation\"}[1m]))",
       "legendFormat": "PUT-COPY total"
      }
     ]
    },
    {
     "title": "S3 PUT average object size",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(http_s3_servlet_put_object_bytes_total[10m]))/sum(rate(http_s3_servlet_operations_total{operation=\"S3PutObjectOperation\"}[10m]))",
       "legendFormat": "PUT"
      }
     ]
    },
    {
     "title": "S3 PUT average object size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 20, "x": 4, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(http_s3_servlet_put_object_bytes_total[10m]))/sum(rate(http_s3_servlet_operations_total{operation=\"S3PutObjectOperation\"}[10m]))",
       "legendFormat": "PUT"
      }
     ]
    },
    {
     "title": "S3 PUT-PART average object size",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(http_s3_servlet_put_object_part_bytes_total[10m]))/sum(rate(http_s3_servlet_operations_total{operation=\"S3PutObjectPartOperation\"}[10m]))",
       "legendFormat": "PUT-PARTS"
      }
     ]
    },
    {
     "title": "S3 PUT-PART average object size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 20, "x": 4, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(http_s3_servlet_put_object_part_bytes_total[10m]))/sum(rate(http_s3_servlet_operations_total{operation=\"S3PutObjectPartOperation\"}[10m]))",
       "legendFormat": "PUT-PARTS"
      }
     ]
    },
    {
     "title": "S3 Ingest Latency (max observed)",
     "type": "barchart",
     "description": "The max observed latency on any node over the reporting period",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "min(bottomk(1,(min(http_s3_servlet_requests_latency_seconds{operation=\"S3PutObjectOperation\"}))))",
       "legendFormat": "PUT {{instance}}"
      },
      {
       "expr": "min(topk(1,(http_s3_servlet_requests_latency_seconds{operation=\"S3PutObjectPartOperation\"})))",
       "legendFormat": "PutPart {{instance}}"
      },
      {
       "expr": "min(topk(1,(http_s3_servlet_requests_latency_seconds{operation=\"S3PutObjectCopyOperation\"})))",
       "legendFormat": "PutCopy {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System S3 Data GET Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Max S3 GET Latency ",
     "type": "stat",
     "gridPos": { "h": 10, "w": 4, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "abs(sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3GetObjectOperation\", le=\"0.1\"}[1m])) - sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3GetObjectOperation\", le=\"0.5\"}[1m])))",
       "legendFormat": ">100ms"
      },
      {
       "expr": "abs(sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3GetObjectOperation\", le=\"0.5\"}[1m])) - sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3GetObjectOperation\", le=\"1.0\"}[1m])))",
       "legendFormat": ">500ms"
      },
      {
       "expr": "abs(sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3GetObjectOperation\", le=\"1.0\"}[1m])) - sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3GetObjectOperation\", le=\"5.0\"}[1m])))",
       "legendFormat": ">1s"
      },
      {
       "expr": "abs(sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3GetObjectOperation\", le=\"5.0\"}[1m])) - sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3GetObjectOperation\", le=\"10.0\"}[1m])))",
       "legendFormat": ">5s"
      },
      {
       "expr": "abs(sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3GetObjectOperation\", le=\"10.0\"}[1m])) - sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3GetObjectOperation\", le=\"50.0\"}[1m])))",
       "legendFormat": ">10s"
      },
      {
       "expr": "abs(sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3GetObjectOperation\", le=\"50.0\"}[1m])) - sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3GetObjectOperation\", le=\"100.0\"}[1m])))",
       "legendFormat": ">50s"
      }
     ]
    },
    {
     "title": "S3 GET Latency Distribution (counts per second)",
     "type": "barchart",
     "gridPos": { "h": 10, "w": 20, "x": 4, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "abs(sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3GetObjectOperation\", le=\"0.1\"}[1m])) - sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3GetObjectOperation\", le=\"0.5\"}[1m])))",
       "legendFormat": ">100ms"
      },
      {
       "expr": "abs(sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3GetObjectOperation\", le=\"0.5\"}[1m])) - sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3GetObjectOperation\", le=\"1.0\"}[1m])))",
       "legendFormat": ">500ms"
      },
      {
       "expr": "abs(sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3GetObjectOperation\", le=\"1.0\"}[1m])) - sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3GetObjectOperation\", le=\"5.0\"}[1m])))",
       "legendFormat": ">1s"
      },
      {
       "expr": "abs(sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3GetObjectOperation\", le=\"5.0\"}[1m])) - sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3GetObjectOperation\", le=\"10.0\"}[1m])))",
       "legendFormat": ">5s"
      },
      {
       "expr": "abs(sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3GetObjectOperation\", le=\"10.0\"}[1m])) - sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3GetObjectOperation\", le=\"50.0\"}[1m])))",
       "legendFormat": ">10s"
      },
      {
       "expr": "abs(sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3GetObjectOperation\", le=\"50.0\"}[1m])) - sum(irate(http_s3_servlet_requests_histogram_latency_seconds_bucket{operation=\"S3GetObjectOperation\", le=\"100.0\"}[1m])))",
       "legendFormat": ">50s"
      }
     ]
    },
    {
     "title": "S3 Read Max Latency",
     "type": "stat",
     "description": "GET Latency during reporting period",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max(http_s3_servlet_requests_latency_seconds{operation=\"S3GetObjectOperation\"})",
       "legendFormat": "GET"
      }
     ]
    },
    {
     "title": "S3 GET Latency (detail by node)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 20, "x": 4, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "http_s3_servlet_requests_latency_seconds{operation=\"S3GetObjectOperation\"}",
       "legendFormat": "GET {{instance}}"
      }
     ]
    },
    {
     "title": "S3 Object GET (READ during period)",
     "type": "stat",
     "description": "Volume of Data read during reporting period",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "delta" ] } },
     "targets": [
      {
       "expr": "sum(http_s3_servlet_get_object_response_bytes_per_bucket{})",
       "legendFormat": "GET"
      },
      {
       "expr": "sum(http_s3_servlet_get_object_response_bytes_per_bucket_total{})",
       "legendFormat": "GET"
      }
     ]
    },
    {
     "title": "Cluster GET Throughput by Node",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 20, "x": 4, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(http_s3_servlet_get_object_response_bytes_total[1m]))",
       "legendFormat": "GET Total"
      },
      {
       "expr": "rate(http_s3_servlet_get_object_response_bytes_total[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "S3 GET IOPS",
     "type": "stat",
     "description": "IOPS of Data Read during reporting period",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "sum(rate(http_s3_servlet_operations_total{operation=\"S3GetObjectOperation\"}[1m]))",
       "legendFormat": "GET"
      }
     ]
    },
    {
     "title": "S3 GET IOPS by Node",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 20, "x": 4, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum(rate(http_s3_servlet_operations_total{operation=\"S3GetObjectOperation\"}[1m]))",
       "legendFormat": "GET Total"
      },
      {
       "expr": "rate(http_s3_servlet_operations_total{operation=\"S3GetObjectOperation\"}[1m])",
       "legendFormat": "GET {{instance}}"
      }
     ]
    },
    {
     "title": "S3 GET Average Size",
     "type": "stat",
     "description": "Current Average Size",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(http_s3_servlet_get_object_response_bytes_total[1m])) / sum(rate(http_s3_servlet_operations_total{operation=\"S3GetObjectOperation\"}[1m]))\r\n\r\n",
       "legendFormat": "GET"
      }
     ]
    },
    {
     "title": "S3 GET Average Size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 20, "x": 4, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(http_s3_servlet_get_object_response_bytes_total[1m])) / sum(rate(http_s3_servlet_operations_total{operation=\"S3GetObjectOperation\"}[1m]))",
       "legendFormat": "GET {{instance}}"
      }
     ]
    },
    {
     "title": "S3 Read Max Latency",
     "type": "stat",
     "description": "GET Latency during reporting period",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max(http_s3_servlet_requests_latency_seconds{operation=\"S3GetObjectOperation\"})",
       "legendFormat": "GET"
      }
     ]
    },
    {
     "title": "S3 GET Latency (max observed)",
     "type": "barchart",
     "description": "The max observed latency on any node over the reporting period",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "(http_s3_servlet_requests_latency_seconds{operation=\"S3GetObjectOperation\"})",
       "legendFormat": "GET {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System S3 Object Delete Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Backlog of Undeleted Objects/Parts on S-nodes.",
   "type": "stat",
   "description": "The number of objects/parts to be deleted on S-nodes. It's NOT the same as the number of client objects to be deleted if S3 multipart upload is used.\nIt's the number of objects/parts to be deleted on S-nodes.\nIt also includes small objects (DEKs) created on S-nodes as a result encryption rekey process, if any.",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(storage_total_objects{store=\"aggregate\"}) - sum(metadata_clientobject_part_active_count)) * (count(sum(lifecycle_policy_rekey_initiated_count_total OR on() vector(0)) ==0) + (count(sum(lifecycle_policy_rekey_initiated_count_total) > 1) OR on() vector(0)) )"
    }
   ]
  },
  {
   "title": "Backlog Percentage of Undeleted Objects/Parts on S-nodes",
   "type": "gauge",
   "description": "The number of objects/parts to be deleted on S-nodes. It's NOT the same as the number of client objects to be deleted if S3 multipart upload is used.\nIt's the number of objects/parts to be deleted on S-nodes.\n",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(storage_total_objects{store=\"aggregate\"} OR on() vector(0)) - sum(metadata_clientobject_part_active_count OR on() vector(0)) - sum(lifecycle_policy_rekey_accept_latency_seconds_count OR on() vector(0)) ) / sum(storage_total_objects{store=\"aggregate\"})"
    }
   ]
  },
  {
   "title": "Total S3 Versioned Delete requests",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_s3_servlet_delete_requests_per_bucket_total{delete_type=\"versioned\"})"
    }
   ]
  },
  {
   "title": "Total S3 Unversioned Delete requests",
   "type": "gauge",
   "description": "The number of S3 Object Delete (unversioned/latest) requests",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_s3_servlet_delete_requests_per_bucket_total{delete_type=\"latest\"})"
    }
   ]
  },
  {
   "title": "S3 Delete Activity",
   "type": "timeseries",
   "description": "Shows the number of Versioned S3 Delete requests and the Unversioned S3 Delete requests",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(http_s3_servlet_delete_requests_per_bucket_total{delete_type=\"versioned\"} OR on() vector(0))",
     "legendFormat": "Versioned Deletes"
    },
    {
     "expr": "sum(http_s3_servlet_delete_requests_per_bucket_total{delete_type=\"latest\"} OR on() vector(0))",
     "legendFormat": "Unversioned Deletes"
    }
   ]
  },
  {
   "title": "S3 Delete Rate",
   "type": "timeseries",
   "description": "Shows the rate of Versioned S3 Delete requests and the Unversioned S3 Delete requests",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_s3_servlet_delete_requests_per_bucket_total{delete_type=\"versioned\"}[10m]) OR on() vector(0))",
     "legendFormat": "Versioned Deletes"
    },
    {
     "expr": "sum(rate(http_s3_servlet_delete_requests_per_bucket_total{delete_type=\"latest\"}[10m]) OR on() vector(0))",
     "legendFormat": "Unversioned Deletes"
    }
   ]
  },
  {
   "title": "DLS: accept rate for Delete Backend Objects and Expire Versions policies",
   "type": "timeseries",
   "description": "DLS policies - Rate of Delete Backend Objects and Expire Versions policies",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(lifecycle_policy_accept_latency_seconds_count{policy=\"DELETE_BACKEND_OBJECTS\"}[10m]))",
     "legendFormat": "DELETED backend objects"
    },
    {
     "expr": "sum(rate(lifecycle_policy_accept_latency_seconds_count{policy=\"VERSION_EXPIRATION\"}[10m]))",
     "legendFormat": "EXPIRED versions"
    }
   ]
  },
  {
   "title": "DLS examine rate: Delete Backend Objects and Version Expiration policies",
   "type": "timeseries",
   "description": "DLS examine rate for Delete Backend Objects and Version Expiration policies",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(lifecycle_policy_examine_latency_seconds_count{policy=\"DELETE_BACKEND_OBJECTS\"}[10m]))",
     "legendFormat": "DELETED backend objects "
    },
    {
     "expr": "sum(rate(lifecycle_policy_examine_latency_seconds_count{policy=\"VERSION_EXPIRATION\"}[10m]))",
     "legendFormat": "EXPIRED versions"
    }
   ]
  },
  {
   "title": "S3 Failed Request Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "S3 Failed Requests ",
     "type": "gauge",
     "description": "Number of S3 Failed Requests - returned errors - within this period",
     "gridPos": { "h": 13, "w": 4, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "http_s3_servlet_errors_total", "legendFormat": "{{error}}" }
     ]
    },
    {
     "title": "S3 Failed Request Detail",
     "type": "table",
     "gridPos": { "h": 13, "w": 8, "x": 4, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (error)(http_s3_servlet_errors_total{})",
       "legendFormat": "{{error}}"
      }
     ]
    },
    {
     "title": "S3 Failed Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "sum by (error)(rate(http_s3_servlet_errors_total{error=~\"InternalError|RequestTimeout\"}[10m]))",
       "legendFormat": "{{error}}"
      }
     ]
    },
    {
     "title": "S3 Failed Requests ",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "sum by (error)(http_s3_servlet_errors_total{error=~\"InternalError|RequestTimeout\"})",
       "legendFormat": "{{error}}"
      }
     ]
    }
   ]
  }
 ]
}