{
 "title": "HCP for Cloud Scale - Dashboard 2: System Overview",
 "tags": [ "cloudscale" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ClusterName", "label": "Choose  Cluster", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   { "name": "allnodes", "label": "WildCard", "query": "${VAR_ALLNODES}" },
   { "name": "excl_net", "label": "Exclude_Device", "query": "^docker.*$|^lo$" }
  ]
 },
 "panels": [
  {
   "title": "System Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Capacity & Objects",
   "type": "gauge",
   "description": "Sortable Capacity per bucket.  Change count be used to identify bucket activity.",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(metadata_total_bytes_per_bucket{})",
     "legendFormat": "Total bytes"
    },
    {
     "expr": "sum(metadata_total_objects_per_bucket{})",
     "legendFormat": "Total objects"
    },
    {
     "expr": "sum(metadata_total_bytes_per_bucket{}) / sum(metadata_total_objects_per_bucket{})",
     "legendFormat": "Average Object Size"
    }
   ]
  },
  {
   "title": "Total Objects",
   "type": "timeseries",
   "description": "The total number of active client objects",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(metadata_clientobject_active_count) ",
     "legendFormat": "Object Count"
    }
   ]
  },
  {
   "title": "New Objects",
   "type": "stat",
   "description": "Reports the current deletes form the last hour. A value of zero could indicate an issue on a busy system",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metadata_clientobject_active_count) - sum(metadata_clientobject_active_count offset 1d) ",
     "legendFormat": "New Objects"
    }
   ]
  },
  {
   "title": "Total Object Count - Client objects and S-node objects",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(metadata_clientobject_active_count)",
     "legendFormat": "Cloud Scale "
    },
    {
     "expr": "sum(storage_total_objects{store=\"aggregate\"})",
     "legendFormat": "S-nodes"
    }
   ]
  },
  {
   "title": "Capacity & Objects per bucket",
   "type": "table",
   "description": "Sortable Capacity per bucket.  Change count be used to identify bucket activity.",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (bucket)(metadata_total_bytes_per_bucket{})",
     "legendFormat": "{{bucket}}"
    },
    {
     "expr": "sum by (bucket)(metadata_total_objects_per_bucket{})",
     "legendFormat": "{{bucket}}"
    },
    {
     "expr": "sum by (bucket)(metadata_total_bytes_per_bucket{}) / sum by (bucket)(metadata_total_objects_per_bucket{})",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Used Capacity ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(metadata_total_bytes_per_bucket)",
     "legendFormat": "Cloud Scale "
    },
    {
     "expr": "sum(storage_total_capacity_bytes{store=\"aggregate\"})",
     "legendFormat": "S-nodes"
    }
   ]
  },
  {
   "title": "Recently Moved Data ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Data Moved (Since Power-On)",
     "type": "stat",
     "description": "Volume of Data written and read during reporting period",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(http_s3_servlet_put_object_bytes_total{})",
       "legendFormat": "PUT"
      },
      {
       "expr": "sum(http_s3_servlet_put_object_part_bytes_total{})",
       "legendFormat": "PUT-PARTS"
      },
      {
       "expr": "sum(http_s3_servlet_put_copied_bytes_total{})",
       "legendFormat": "PUT-COPY"
      },
      {
       "expr": "sum(http_s3_servlet_get_object_response_bytes_per_bucket_total{})",
       "legendFormat": "GET"
      },
      {
       "expr": "sum(http_s3_servlet_get_object_response_bytes_per_bucket{})",
       "legendFormat": "GET"
      }
     ]
    },
    {
     "title": "Data Moved (Since Power-on)",
     "type": "timeseries",
     "description": "Volume of Data written and read during reporting period",
     "gridPos": { "h": 8, "w": 17, "x": 7, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(http_s3_servlet_put_object_bytes_total{})",
       "legendFormat": "PUT"
      },
      {
       "expr": "sum(http_s3_servlet_put_object_part_bytes_total{})",
       "legendFormat": "PUT-PARTS"
      },
      {
       "expr": "sum(http_s3_servlet_put_copied_bytes_total)",
       "legendFormat": "PUT-COPY"
      },
      {
       "expr": "sum(http_s3_servlet_get_object_response_bytes_per_bucket{})",
       "legendFormat": "GET"
      },
      {
       "expr": "sum(http_s3_servlet_get_object_response_bytes_per_bucket_total{})",
       "legendFormat": "GET"
      }
     ]
    }
   ]
  },
  {
   "title": "Object Count Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "Cloud Scale Object Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metadata_clientobject_active_count)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "S-node Total Object Count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 7, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "storage_total_objects{store=\"aggregate\"}",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Backlog of Undeleted Objects/Parts on S-nodes.",
   "type": "stat",
   "description": "The number of objects/parts to be deleted on S-nodes. It's NOT the same as the number of client objects to be deleted if S3 multipart upload is used.\nIt's the number of objects/parts to be deleted on S-nodes.\nIt also includes small objects (DEKs) created on S-nodes as a result encryption rekey process, if any.",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(storage_total_objects{store=\"aggregate\"}) - sum(metadata_clientobject_part_active_count)) * (count(sum(lifecycle_policy_rekey_initiated_count_total OR on() vector(0)) ==0) + (count(sum(lifecycle_policy_rekey_initiated_count_total) > 1) OR on() vector(0)) )"
    }
   ]
  },
  {
   "title": "S-node Object Count breakdown",
   "type": "table",
   "description": "Table of capacity by S-node",
   "gridPos": { "h": 10, "w": 8, "x": 7, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "storage_total_objects{store!=\"aggregate\"}",
     "legendFormat": "{{store}}"
    }
   ]
  },
  {
   "title": "Cloud Scale Object Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(metadata_clientobject_active_count)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Undeleted Objects Backlog ",
   "type": "gauge",
   "description": "Storage Object Recovery Queue",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(storage_total_objects{store=\"aggregate\"}) - sum(metadata_clientobject_part_active_count)) * (count(sum(lifecycle_policy_rekey_initiated_count_total OR on() vector(0)) ==0) + (count(sum(lifecycle_policy_rekey_initiated_count_total) > 1) OR on() vector(0)) ) / sum(storage_total_objects{store=\"aggregate\"})"
    }
   ]
  },
  {
   "title": "System Capacity Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Cloud Scale Used Capacity",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(metadata_total_bytes_per_bucket)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "S-node Total Used Capacity",
     "type": "stat",
     "gridPos": { "h": 4, "w": 7, "x": 5, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "storage_used_capacity_bytes{store=\"aggregate\"}",
       "legendFormat": "All"
      }
     ]
    },
    {
     "title": "Snode Used Capacity breakdown",
     "type": "table",
     "description": "Table of capacity by S-node",
     "gridPos": { "h": 6, "w": 7, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "storage_used_capacity_bytes{store!=\"aggregate\"}/storage_total_capacity_bytes{store!=\"aggregate\"}",
       "legendFormat": "{{store}}"
      }
     ]
    }
   ]
  }
 ]
}